---
- hosts: all
  sudo: yes
  # vars_files: vars.yaml

  tasks:
    - name: Install apache server
      yum: name=httpd state=present
      notify: restart apache

    - name: Add centos-release-scl
      yum: name=centos-release-scl state=present

    - name: Install apache, MySQL, PHP and others
      yum: name={{ item }} state=present
      with_items:
        - git
        - curl
        - sendmail
        - httpd
        - wget
        - unzip
        - php-xml
        - php-pear
        - php-fpm
        - php55
        - php55-php
        - php55-php-mysqlnd
        - php55-php-gd
        - php55-php-mbstring
        - python-mysqldb
        - mariadb-server

    - name: Stop firewall
      service: name=firewalld state=stopped enabled=false

    - name: Start apache, MySQL and PHP
      service: name={{ item }} state=started enabled=true
      with_items:
        - httpd
        - mariadb

  handlers:
    - name: restart apache
      service: name=httpd state=restarted enabled=true